<?php

class PDF extends \fpdf\FPDF
{
    private $assets = "../assets/";

// Page header
    function Header()
    {
        $this->SetFont('Arial','B',20);
        $this->MultiCell(150,4,'Förderverein Jugendtreff Mutterstadt e.V.',0,1);   //leerzeile
        $this->Image($this->assets.'logo.jpg',125,35,55,0,'JPG');  //logo

        $this->Ln(3);

        $this->SetFont('Arial','',9);
        $this->Cell(50,4,'E-Mail: info@juzmu.de  /  Tel.: 555-123 123 22',0,1);
        /*$this->Cell(50,4,'info@juzmu.de',0,1);
        $this->Cell(50,4,'Tel.: ',0,1);
        $this->Cell(50,4,'555-12325354',0,1);*/

        $this->Ln(8);

        $this->SetDrawColor(230,230,230);
        $this->SetFont('Arial','',8);
        $this->MultiCell(90,4,"Förderverein Jugendtreff Mutterstadt e.V,\n Oggersheimerstraße 10, 67112 Mutterstadt",1,'C');
        $this->SetFont('Courier','', 12);
        $this->MultiCell(90,4,"\n\nGemeindeverwaltung Mutterstadt\nOggersheimerstr. 10\n\n67112 Mutterstadt\n\n\n",1,'L');

        $monate = array("Jannuar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember");
        $timestamp= time();
        $monat = $monate[date('n', $timestamp)];
        $timestamp= time();
        $jahr = date(" Y",$timestamp);
        $tag = date("d. ",$timestamp);

        $this->Ln(20);

        $this->SetFont('Arial','',12);
        $this->Cell(0,4,$tag . $monat . $jahr,0,1,'R');

        //falzlinie
        $this->Line(0, 87, 10, 87);
        $this->Line(0 , 192, 10 , 192);
    }

// Page footer
    function Footer()
    {
        // Position at 1.5 cm from bottom
        $this->SetY(-15);
        // Arial italic 8
        $this->SetFont('Arial','',8);
        // Page number
        $this->Cell(0,10,'Seite '.$this->PageNo().' von {nb}',0,0,'C');
    }

    function MultiCell($w, $h, $txt, $border = 0, $align = 'J', $fill = false)
    {
        parent::MultiCell($w, $h, utf8_decode($txt), $border, $align, $fill); // TODO: Change the autogenerated stub
    }

}
